MRG: fix lint error, & processed sig reporting for rocksdb/fastmultigather (#320)
Fixes https://github.com/sourmash-bio/sourmash_plugin_branchwater/issues/313
Fixes https://github.com/sourmash-bio/sourmash_plugin_branchwater/issues/285

Addresses #239 / #299 by bailing out when an output path is provided but will not be used:
```
RuntimeError: output path specified, but not running fastmultigather against a rocksdb. See 
issue #239
```
although we are leaning towards respecting `-o` in the future, see #299 discussion, so this will soon get revisited.
---------

Co-authored-by: Tessa Pierce Ward <bluegenes@users.noreply.github.com>